### ISSUE TITLE
Issue in shellscript wireguard.sh

### ISSUE THREAD

**Issue by a-dekker** [javitonino/connman-plugin-vpn-wireguard#1]
This part of the script will `exit 1` with a `unbound variable` error if no keepalive value is set: https://github.com/javitonino/connman-plugin-vpn-wireguard/blob/6004926075ac1d64b38ddc0c9b007c96bc5379d6/wireguard.sh#L2-L4
You can't refer to a variable that might not exist when using `set -u`

**Comment by javitonino** [comment]
Yes, this is true. However, is this causing any problems? The plugin always sets that environment variable. This check is checking if it's set to an empty string to set it to zero instead. But the env variable should be set.

Are you running the script directly? Or as part of the plugin?

**Comment by a-dekker** [comment]
It's been a while, but as far as I remember it gave issues if keepalive was left empty. But maybe I was facing another issue.

I added a keepalive value but also de-installed connman-plugin-vpn-wireguard a while ago because of https://openrepos.net/comment/41482#comment-41482, so I can't test any further. I'll close the issue then.
